plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - europe-west1-b
projects:
  - cursusm2i-maxence
service_account_file: ./service_account.json
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE labels
  - key: labels
    prefix: label
  - key: zone
    prefix: zone
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
